/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
	// By default, Docusaurus generates a sidebar from the docs folder structure
	userSidebar: [
		'index',
		{
			type: 'category',
			label: 'Concepts',
			link: {
				type: 'generated-index',
				title: 'Mailchain Concepts',
				description: 'Learn more about Mailchain concepts.',
				slug: 'user/category/concepts',
				keywords: ['concepts'],
			},
			items: [{ type: 'autogenerated', dirName: 'user/concepts' }],
		},
		{
			type: 'category',
			label: 'Guides & Tutorials',
			collapsed: false,
			link: {
				type: 'generated-index',
				title: 'Guides & Tutorials',
				description: 'This section contains guides and tutorials to help you with Mailchain.',
				slug: 'user/guides',
				keywords: ['guides', 'tutorial'],
			},
			items: [
				{
					type: 'category',
					label: 'Getting Started Guides',
					link: {
						type: 'generated-index',
						title: 'Getting Started With Mailchain',
						description: 'Learn how to create an account, and start sending and receiving messages.',
						slug: 'user/guides/getting-started',
						keywords: ['guides', 'tutorial', 'getting started'],
						// image: '/img/docusaurus.png',
					},
					items: [{ type: 'autogenerated', dirName: 'user/guides/getting-started' }],
					collapsed: false,
				},
				{
					type: 'category',
					label: 'Web3 Domain Names',
					collapsed: false,
					link: {
						type: 'generated-index',
						title: 'Web3 Domain Name Guides',
						slug: 'user/guides/name-services',
						keywords: ['guides', 'name service'],
					},
					items: [
						{
							type: 'category',
							label: 'Aurora (.aurora)',
							collapsed: true,
							link: {
								type: 'generated-index',
								slug: 'user/guides/name-services/aurora/',
								keywords: ['guides', 'name service'],
							},
							items: [
								'user/guides/name-services/aurora/aurora-getting-started',
								'user/guides/name-services/aurora/aurora-faqs',
							],
						},
						{
							type: 'category',
							label: 'Coinbase Decentralized ID (cb.id)',
							collapsed: true,
							link: {
								type: 'generated-index',
								slug: 'user/guides/name-services/coinbase-decentralized-id/',
								keywords: ['guides', 'name service'],
							},
							items: [
								'user/guides/name-services/coinbase-decentralized-id/coinbase-decentralized-id-getting-started',
								'user/guides/name-services/coinbase-decentralized-id/coinbase-decentralized-id-faqs',
							],
						},
						{
							type: 'category',
							label: 'ENS (.eth)',
							collapsed: true,
							link: {
								type: 'generated-index',
								slug: 'user/guides/name-services/ens/',
								keywords: ['guides', 'name service'],
							},
							items: [
								'user/guides/name-services/ens/ens-getting-started',
								'user/guides/name-services/ens/ens-faqs',
							],
						},
						{
							type: 'category',
							label: 'Freename TLDs & SLDs',
							collapsed: true,
							link: {
								type: 'generated-index',
								slug: 'user/guides/name-services/freename/',
								keywords: ['guides', 'name service'],
							},
							items: [
								'user/guides/name-services/freename/freename-getting-started',
								'user/guides/name-services/freename/freename-faqs',
							],
						},
						{
							type: 'category',
							label: 'Lens Protocol (.lens)',
							collapsed: true,
							link: {
								type: 'generated-index',
								slug: 'user/guides/name-services/lens/',
								keywords: ['guides', 'name service'],
							},
							items: [
								'user/guides/name-services/lens/lens-getting-started',
								'user/guides/name-services/lens/lens-faqs',
							],
						},
						{
							type: 'category',
							label: 'Unstoppable Domains',
							collapsed: true,
							link: {
								type: 'generated-index',
								slug: 'user/guides/name-services/unstoppable-domains/',
								keywords: ['guides', 'name service'],
							},
							items: [
								'user/guides/name-services/unstoppable-domains/unstoppable-domains-getting-started',
								'user/guides/name-services/unstoppable-domains/unstoppable-domains-faqs',
							],
						},
					],
				},
				{
					type: 'category',
					label: 'Account & Settings',
					link: {
						type: 'generated-index',
						title: 'Mailchain Settings',
						slug: 'user/guides/settings',
						keywords: ['guides', 'settings'],
					},
					items: [{ type: 'autogenerated', dirName: 'user/guides/settings' }],
				},
			],
		},
	],
	developerSidebar: [
		{
			type: 'doc',
			id: 'developer/index',
			label: 'Introduction',
		},

		{
			type: 'category',
			label: 'Getting Started',
			// link: {
			// 	// slug: 'developer/getting-started',
			// 	// type: 'generated-index',
			// },
			collapsed: false,
			items: ['developer/installation', 'developer/address-formatting'],
		},
		{
			type: 'category',
			label: 'Quickstart',
			// link: {
			// 	type: 'generated-index',
			// },
			collapsed: false,
			items: ['developer/guides/authenticate', 'developer/guides/send'],
			// items: ['developer/guides/authenticate', 'developer/guides/send', 'developer/guides/register-address'],
			//sss
		},
		{
			type: 'category',
			label: 'Tutorials',
			collapsed: false,
			items: [
				'developer/tutorials/send-via-api',
				'developer/tutorials/authenticated-webhook',
				{
					type: 'category',
					label: '🔒 Authentication Integrations',
					collapsed: false,
					items: [
						'developer/tutorials/integrations/passport-magic-link-tutorial',
						'developer/tutorials/integrations/stytch-magic-link',
					],
				},
				{
					type: 'category',
					label: '🔔 On-chain Events & Notifications',
					collapsed: false,
					items: [
						'developer/tutorials/integrations/send-mail-on-address-activity-alchemy-notify',
						'developer/tutorials/integrations/hal-notify-on-chain-notifications',
						'developer/tutorials/integrations/tenderly-on-chain-event-notifications',
					],
				},
			],
		},
		{
			type: 'category',
			label: 'Other Resources',
			collapsed: false,
			items: ['developer/resources/cla'],
		},
	],
};

module.exports = sidebars;
